#!/usr/bin/env python

import random
import string
import os
import keyring
import glib
import gnomekeyring
import subprocess

glib.set_application_name('homesync')

gnomekeyring.set_default_keyring_sync('login')

username = os.environ['USER']
salt = '%x' % random.getrandbits(16*4)
pw = ''.join([random.choice(string.printable) for i in range(128)])

gnomekeyring.set_network_password_sync('login', 'waltermundt', 'homesync',
                             None, None, None, None, 0, salt+pw)

print salt+pw

